- bundle.yaml
and expose the right services.
> Increment the revision of kubernetes, and etcd.

- bundle.yaml
Updated revision:
kubernetes to 4
filebeat to 2
topbeat to 2
kibana to 4
> Bumping revision numbers on kubernetes and other charms.

- bundle.yaml
> Add "beats" dashboard option to bundle (fixes #10)

- README.md
- bundle.yaml
Addresses the issues with the README #11, #12, #13
> Fixing readme issues

- README.md
- bundle.yaml
Addressing issue #9 and #10.
@chuckbutler will notice I changed "grab" to "download"
@arosales Please let me know if this resolves your issues.
> Adding information about Kibana and dashboards.

- bundle.yaml
> Bump the charm revisions in the bundle

- conjure/steps/00_deploy-done
Fix the deploy done script to handle the active applications and the
elasticsearch status being in unknown/idle.
Signed-off-by: Adam Stokes <adam.stokes@ubuntu.com>
> Adjust our deploy-done script

- README.md
- bundle.yaml
I ran through the readme and fixed up the documentation. I also made the constraints generic so we can run on GCE ootb.
Fixes issue #28
> More generic constraints

- README.md
at this time, i would like to propose an additional fix to the :hamburger: readme, at this time.
> :hamburger: for matt

- bundle.yaml
- tests/10-deploy.py
- tests/tests.yaml
Please look over these changes
> Bumped several charms, fixed tests, and yaml.

- README.md
Add Juju 2.x syntax for the service to application rename.
> Juju 1.x and 2.x syntax for service|applicaiton

- tests/10-deploy.py
- tests/tests.yaml
Adding the tests from kubernetes-core.
> Adding the new tests to observable bundle.

- README.md
> cute little badges

- README.md
Adds the new components and walks the user through fetching credentials,
scaling, and launching workloads in their newly deployed kubernetes
cluster
> refactored the readme for some user-guide changes

- bundle.yaml
> This is the new master/node split bundle.

- local.yaml
- tests/tests.yaml
and commented tests.yaml with test plan
> Added local.yaml definition for testing support

- README.md
I also changed some paragraphs to be less than 80 columns.
I added some words on Ingress and what it is.
Fixed some other spots.
> Attempting to fix rendering problems on jujucharms.com (again)!

- README.md
The charm store did not render the last bundle correctly.
> Fixing the preformatted blocks by trial and error.

- README.md
I'd like to suggest a change to the conjure-up section that includes a little more detail about what conjure-up does
> Provide more detail about conjure-up

- README.md
- bundle.yaml
Additionally bumps the bundle to the latest revisions of flannel,
k8s-master and k8s-worker
> Updates the README with dashboard access info

- README.md
- bundle.yaml
This will point to the most current flannel charm.
> Incrementing flannel to the latest in the store, and updating readme.

- README.md
@chuckbutler @mbruzek @Cynerva 
#39 #61 #63
> update docs to explain proxy configuration

- README.md
Outcome of #70, updated README with more info on LXD limitations.
> Update README with LXD limitations

- bundle.yaml
Version bump with our work today.
> Incrementing the revision for kubeapi-load-balancer and kubernetes-worker.

- README.md
Plus other formatting updates.
> Adding storage information to the README.

- tests/tests.yaml
This reverts commit 844b142346166369e50a106c4bbd3a12487a0860.
> Revert "Remove the test plan packages"

- bundle.yaml
Adding the work that was done last week.
> Incrementing the revision of master, worker, and easyrsa.

- bundle.yaml
- local.yaml
- tests/20-basic-component-check.py
aws/us-east-2 bundletester results.
PASS: 15 Total: 15 (576.778627 sec)
> Test improvements, and bumping versions of master and worker.

- README.md
Juju 2.0 instruction update fixes #128
> Juju 2.0 instruction update fixes #128

- bundle.yaml
* removes elastic charms
* upgrades to v1.5.1
* CNI
* etcd using easyrsa charm for TLS
> release v1.5.1

- README.md
@chuckbutler @mbruzek @Cynerva
> remove references to the elastic stack from the docs

- bundle.yaml
@mbruzek Bump kubernetes-master to pick up https://github.com/juju-solutions/kubernetes/pull/93
> Bump revision of kubernetes-master

- fragments/cni/flannel/README.md
- fragments/k8s/cdk/README.md
- fragments/k8s/core/README.md
See https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/180
> document manual resource installation

- fragments/k8s/core/README.md
Add new install steps for conjure-up
> k8s-core conjure-up install steps update

- fragments/k8s/cdk/README.md
Update install instructions for conjure-up
> k8s-cdk conjure-up install steps update

- tests/20-basic-component-check.py
> Find etcd binary under snap

- tests/20-charm-validation.py
- tests/amulet_utils.py
Also adds an etcd scale test to validate that
https://github.com/kubernetes/kubernetes/issues/43461 does not surface
again
> Cleanup the bundle tests to work post snap refactor

- tests/30-kubernetes-e2e-check.py
I don't feel great about the TEST_RESULT_DIR env var, but this gives us a way to get the results from e2e without printing directly to stdout (which fails with bundletester's xml reporter, due to non-ascii characters).
> Update e2e bundle test to store results

- fragments/k8s/core/bundle.yaml
> First pass at a description for core bundle

- tests/20-charm-validation.py
Two changes:
- The CI was timing out on the spawning 2 workers (takes more than 5 mins)
- Since the security patch went querying the LB is now protects
> Tune scale masters test

- tests/40-security-check.py
These tests can go in after https://github.com/kubernetes/kubernetes/pull/47835 has been merged.
> Add tests for securing the deployment

- tests/20-charm-validation.py
Missing import from my prev PR
> Add missing import

- fragments/k8s/cdk/README.md
- fragments/k8s/cdk/bundle.yaml
- fragments/k8s/core/README.md
- fragments/k8s/core/bundle.yaml
DO NOT MERGE THIS YET. We first need 1.7/stable snaps
> Update bundles and README with 1.7.0 refs

- fragments/k8s/cdk/bundle.yaml
- fragments/k8s/core/bundle.yaml
Fixes #338 
I've tested the kubernetes-core bundle built from this. Will give canonical-kubernetes a go tomorrow.
> Add worker constraints: 4 cores and 4GB RAM

- bundle
- fragments/k8s/cdk/bundle.yaml
- fragments/k8s/core/bundle.yaml
Something to note I put everything on a single line in the bundle fragments so that it goes out as a single line. So it gets displayed correctly on html pages.
> Fix the description wrap-up

- fragments/k8s/cdk/README.md
- fragments/k8s/core/README.md
The command in the doc doesn't seem to work. Not sure if the fix is the best approach, but at least it works. :)
> Minor doc fix on scaling kubernetes-worker with different constraints.

- fragments/k8s/cdk/bundle.yaml
- fragments/k8s/core/bundle.yaml
> add root disk constraints

- fragments/k8s/cdk/bundle.yaml
- fragments/k8s/core/bundle.yaml
Lets put some etcd 3.2 deployments in the CI
> Deploy etcd 3.2

- fragments/k8s/cdk/README.md
- fragments/k8s/core/README.md
Fixes https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/562
> Update the dashboard URL

- fragments/k8s/cdk/README.md
- fragments/k8s/cdk/bundle.yaml
- fragments/k8s/cdk/getstarted.md
These can change over time so let's avoid the maintenance burden of
keeping the prose up-to-date with the bundle.
Fixes #611.
> Update descriptive text to remove specific machine counts.

- fragments/k8s/cdk/README.md
Addresses https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/722
> Cleaning up README

- overlays/monitoring-pgt-overlay.yaml
For https://github.com/charmed-kubernetes/kubernetes-docs/pull/247
> Add overlay for monitoring

- fragments/k8s/cdk-converged/bundle.yaml
- fragments/k8s/cdk/bundle.yaml
- fragments/k8s/core/bundle.yaml
Move channels in preparation for 1.16/stable
> move bundle channels to 1.16/stable

- fragments/k8s/cdk/README.md
> new URL for dashboard in 1.16

- fragments/k8s/cdk-converged/bundle.yaml
- fragments/k8s/cdk/bundle.yaml
- fragments/k8s/core/bundle.yaml
update fragments for 1.17/stable
> bump to 1.17 release

- fragments/k8s/cdk-converged/README.md
- fragments/k8s/cdk/README.md
- fragments/k8s/core/README.md
For the bundle READMEs seen in the charm store.
> Bump fragment READMEs to 1.17

- fragments/k8s/cdk-converged/README.md
- fragments/k8s/cdk-converged/bundle.yaml
- fragments/k8s/cdk/README.md
- fragments/k8s/cdk/bundle.yaml
- fragments/k8s/core/README.md
- fragments/k8s/core/bundle.yaml
Now that 1.17 is released to stable, move the master branch up to 1.18.
> start tracking the 1.18 release

- overlays/vault-pki-ha-overlay.yaml
Adds a new overlay for using Vault in HA mode for PKI.
> Add overlay for Vault HA

- overlays/ceph-fs.yaml
- overlays/ceph-rbd.yaml
Adds an overlay for Ceph RBD only, as well as Ceph RBD plus CephFS.
> Add overlays for Ceph

- fragments/k8s/cdk-converged/README.md
- fragments/k8s/cdk-converged/bundle.yaml
- fragments/k8s/cdk/README.md
- fragments/k8s/cdk/bundle.yaml
- fragments/k8s/core/README.md
- fragments/k8s/core/bundle.yaml
Signed-off-by: Adam Stokes <battlemidget@users.noreply.github.com>
> Bump to 1.19/edge for k8s and 3.4/stable for etcd

- fragments/k8s/cdk/bundle.yaml
fixes https://bugs.launchpad.net/charmed-kubernetes-bundles/+bug/1873044
> Increase constraints for k-l-b to 4G

- overlays/vault-pki-ha-overlay.yaml
- overlays/vault-pki-overlay.yaml
Update the vault charm used in the vault overlays
> Update vault overlays

- overlays/bdc-overlay.yaml
overlay for kubernetes-core deployment of a cluster for SQL BDC
> Add  overlay for SQL BDC

- fragments/k8s/cdk-converged/README.md
- fragments/k8s/cdk-converged/bundle.yaml
- fragments/k8s/cdk/README.md
- fragments/k8s/cdk/bundle.yaml
- fragments/k8s/core/README.md
- fragments/k8s/core/bundle.yaml
Now that 1.22 is going stable, move our master branches up to 1.23/edge.
> make 1.23/edge the default channel

- specs/equinix-bundle.yaml
Temporarily add a special bundle for equinix
> Add equinix bundle

- fragments/k8s/cdk-converged/bundle.yaml
- fragments/k8s/cdk/bundle.yaml
- fragments/k8s/core/bundle.yaml
Waiting for the 1.24/stable snaps to be ready
> make 1.24/stable the default channel

- fragments/k8s/cdk-converged/README.md
- fragments/k8s/cdk-converged/bundle.yaml
- fragments/k8s/cdk/README.md
- fragments/k8s/cdk/bundle.yaml
- fragments/k8s/core/README.md
- fragments/k8s/core/bundle.yaml
prep bundles for the 1.25 hand-off to QA
> adjust snap channels for 1.25

- fragments/k8s/cdk-converged/bundle.yaml
- fragments/k8s/cdk/bundle.yaml
- fragments/k8s/core/bundle.yaml
update defaults to 1.26/stable snaps
> Update to select 1.26/stable snaps

- overlays/vsphere-overlay.yaml
- Updated the vSphere overlay to use the `vsphere-cloud-provider`.
> Update vSphere overlay

- overlays/aws-storage-overlay.yaml
- overlays/gcp-storage-overlay.yaml
[LP:2008582](https://bugs.launchpad.net/charmed-kubernetes-bundles/+bug/2008582)
> adding cloud provider storage overlays

- fragments/k8s/cdk-converged/README.md
- fragments/k8s/cdk-converged/bundle.yaml
- fragments/k8s/cdk/README.md
- fragments/k8s/cdk/bundle.yaml
- fragments/k8s/core/README.md
- fragments/k8s/core/bundle.yaml
Per [release checklist](https://github.com/charmed-kubernetes/jenkins/blob/main/docs/releases/stable/index.md#pin-snap-channel-on-bundlescharms-in-the-release-branches)
> update charms and badges for 1.27/stable

- fragments/k8s/cdk-converged/README.md
- fragments/k8s/cdk-converged/bundle.yaml
- fragments/k8s/cdk/README.md
- fragments/k8s/cdk/bundle.yaml
- fragments/k8s/core/README.md
- fragments/k8s/core/bundle.yaml
* bump snap channel defaults from 1.27/edge to 1.28/edge
* update bundle in the charm READMEs
> update fragments to point to 1.28/edge snap channels

- fragments/k8s/cdk-converged/bundle.yaml
- fragments/k8s/cdk/bundle.yaml
- fragments/k8s/core/bundle.yaml
Per [release checklist](https://github.com/charmed-kubernetes/jenkins/blob/main/docs/releases/stable/index.md#pin-snap-channel-on-bundlescharms-in-the-release-branches)
> update snap channels for 1.28/stable

- overlays/openstack-lb-overlay.yaml
- overlays/openstack-overlay.yaml
Fix a couple small errors from previous 1.29 o7k overlay updates.
> follow-on to #889, minor fixes to the o7k overlays
