charmed-kubernetes/bundle

README.md
bundle.yaml
conjure/metadata.json
conjure/steps/00_pre.sh
conjure/steps/01_get-kubectl.sh
conjure/steps/lxd-profile.yaml

This is the first bundle that I've 'enabled' to be used with conjure-up. Basically we place all of our needed metadata inside the conjure/ directory.
This is just the first step in getting it ready. I am still working with the charmstore api to get the other end of the metadata added so it can be searchable down the road.
Testing this out with the latest conjure-up is pretty straightforward, as of this writing you'll want to use the headless mode for now:
```
sudo apt-add-repository ppa:conjure/next
sudo apt update
sudo apt install conjure-up
conjure-up juju-solutions/bundle-observable-kubernetes to localhost
```
This will go through and bootstrap juju, deploy the bundle, setup the lxd profile for use with the juju model, and perform a post step to download kubectl for further use of the …

make bundle conjure-up enabled

---

README.md

Looks like kubectl renamed cluster-health to cluster-info; update
readme to reflet that.
Signed-off-by: Adam Stokes <adam.stokes@ubuntu.com>

Fix kubectl cluster-health command

---

conjure/metadata.json

Kubernetes and friends don't really work that well under LXD/Localhost,
so we blacklist that cloud for now. This gives the user only the options
of all supported public clouds from juju in addition to MAAS.
Signed-off-by: Adam Stokes <adam.stokes@ubuntu.com>

add localhost to cloud-blacklist

---

bundle.yaml

To not confuse people keep the tags prefixed with the same name as the
application 'conjure-up' vs 'conjure'
Signed-off-by: Adam Stokes <adam.stokes@ubuntu.com>

update tag for name consistency

---

README.md

Adds blurb under the known limitations section about 1.25 deployment
behavior with both ZFS (on trusty) and Etcd (resource failure on trusty
series)
Fixes #27

Updates the readme to call out 1.25 limitations

---

bundle.yaml

This release adds Operational Actions to the juju charm, where the
operator can pause/resume nodes.
Test run results:
```
PASS: 16 Total: 16 (1244.214486 sec)
```

Bumps kubernetes to the latest release

---

bundle.yaml

Bumps ES charm to rev 18. Status now sets to 'active' and Ready on extant services/start invocation.

Bumps Elasticsearch to -18 for messaging fix

---

README.md

I had Didier check the README since he's deployed k8s, his only feedback is that it wasn't obvious to him where he should go if he was a developer and didn't want the full hog production grade k8s. This fixes the readme to send people to the right place.

Add mention of kubernetes-core and kubeup.sh for developers.

---

README.md

Currently, sub-bullets appear for the last two items.
I've moved all the indents to match this in an effort to clean up the presentation

Attempt to rectify indented lists

---

README.md

@mbruzek The README told me to do this:
```
$ kubectl get pv --all-namespaces
NAMESPACE   NAME      CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM     REASON    AGE
persistentVolume is not namespaced
persistentVolume is not namespaced
persistentVolume is not namespaced
persistentVolume is not namespaced
```
I had to remove --all-namespaces:
```
$ kubectl get pv
NAME      CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS      CLAIM     REASON    AGE
test      0          RWO           Retain          Available                       13m
test2     50M        RWO           Retain          Available                       10m
test3     50M        RWO           Retain          Available                       8m
test4     100G       RWO           Retain          Available …
```

README: remove --all-namespaces from kubectl get pv command

---

tests/tests.yaml

The ppa/test-plan packages have created a packaging vortex of
dependencies that cannot be resolved at present. This removes those and
relies on the test env to have current 2.0 test tooling. This may be
problematic in the future, but is a necessary change for now.

Remove the test plan packages

---

README.md

Updated README to go with [https://github.com/juju-solutions/kubernetes/pull/65](https://github.com/juju-solutions/kubernetes/pull/65) (not merged yet)
[Link to view README](https://github.com/juju-solutions/bundle-canonical-kubernetes/tree/gkk/dashboard-readme-updates)
I couldn't really come up with much to say, apologies if I'm missing something obvious.
@chuckbutler @mbruzek

Updated README with dashboard addon info

---

bundle

If you call "bundle" from outside the directory it is in tests directory will not be found. This PR fixes this.

Fix: grab tests dir from the projects root_path

---

fragments/k8s/cdk/README.md
fragments/k8s/core/README.md

The version depends on what resource is uploaded to the charm at the time. This is not something that is tied to the bundle metadata. It is tied to the resource which is a separate process. The person who added these "cute" little badge is not keeping the versions current and I can not think of a way to do this automatically in our CI system so I am removing the version badges now.

Removing version badges as they are not tied to bundles data.

---

bundle
fragments/cni/calico/ci-info.yaml
fragments/cni/flannel/ci-info.yaml
fragments/k8s/cdk/ci-info.yaml
fragments/k8s/core/ci-info.yaml
fragments/monitor/elastic/ci-info.yaml

I am not totally sold on this approach. Consider this PR as an RFC.
We need to have a ci-info.yaml inside the bundles so that cwr ci would know which charms would need updating and releasing.

Create bundles that include the ci-info.yaml file

---

tests/20-charm-validation.py
tests/tests.yaml

Fix failing tests in two ways:
1. Exclude charm tests from running (we run these separately)
2. Use properties to allow for dynamic scaling of applications
To elaborate a bit on the properties, this is the failure I was seeing:
```
Traceback (most recent call last):
File "/tmp/bundletester-ZqEPa8/wd/tests/20-charm-validation.py", line 177, in test_etcd_scale_on_master
self.assertTrue(len(split_servers) == len(self.etcds))
AssertionError: False is not true
```
This happens because `self.etcds` is not updated after removing a unit of etcd.
Not only is this a problem for the assert in `test_etcd_scale_on_master`, but it also has the potential to mess up other tests as well - `self.etcds` is a list that's generated only once during `setUpClass`, and is shared across multiple tests.
Rewriting …

Fix failing tests

---

tests/30-kubernetes-e2e-check.py

I'm seeing failures in CI, but don't have visibility into them. This updates the test to write e2e results to stdout on failure.

improve output of e2e test

---

tests/20-charm-validation.py

These two tests expose the following issues:
- https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/299
- https://github.com/kubernetes/kubernetes/issues/47176
I would suggest we do the merge after the respective PRs are accepted so we do not break our CI.

Add tests for labels and master restart action

---

tests/20-charm-validation.py

This PR tests this issue: https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/311
A potential fix for the above issue is here: https://github.com/kubernetes/kubernetes/pull/48054

Add test that scales masters

---

tests/40-security-check.py

@ktsakalozos I'm troubleshooting this failure:
```
DEBUG:runner:Traceback (most recent call last):
DEBUG:runner:  File "/tmp/bundletester-m0ERzU/bundle-under-test/tests/40-security-check.py", line 73, in test_basic
DEBUG:runner:    self.assertTrue(status == 200)
DEBUG:runner:AssertionError: False is not true
```
This PR just updates the test to use `assertEqual` so we can see what status we're hitting.
I don't have capacity to run this locally ATM so I was hoping we could check this in, kick it off on Jenkins, and revisit later.

Improve assert output in security tests

---

tests/20-charm-validation.py

This is a test that should be applied on-top of the PR that tests removing the masters (https://github.com/juju-solutions/bundle-canonical-kubernetes/pull/317)  so pelase merge that one first. The reason is that this tests removes a worker while the master is down.

Clean worker unit removal

---

tests/20-charm-validation.py

Reverts juju-solutions/bundle-canonical-kubernetes#319
Until https://github.com/kubernetes/kubernetes/pull/48144 gets merged upstream.

Revert "Clean worker unit removal"

---

fragments/k8s/cdk/bundle.yaml
fragments/k8s/core/bundle.yaml

cpu-cores is deprecated:
```
$ juju add-machine --constraints cpu-cores=1
Warning: constraint "cpu-cores" is deprecated in favor of "cores".
created machine 0
```
More importantly, it's breaking conjure-up deployments:
```
$ conjure-up --channel edge kubernetes-core aws/us-east-1 aws-dev test
[info] Summoning kubernetes-core to aws/us-east-1
[info] Running step: pre-deploy.
[error] Unsupported constraint: cpu-cores
[warning] Shutting down
```

Revert "Use cpu-cores instead cores in constraints (#351)"

---

fragments/k8s/cdk/README.md
fragments/k8s/core/README.md

I took out the "three node" / "two-node" bit because it seems like it'd only cause confusion. Hope that's okay.

Fix node counts in bundle docs

---

fragments/k8s/cdk/README.md

Two small spelling fixes for https://jujucharms.com/canonical-kubernetes/

Fix spelling of persistent in bundle readme

---

README.md

Reading over the readme, I had to double-take the foo before I realized it was a directory. Changing the wording some to hopefully clear that up for others.

Updating readme to hopefully clarify it some

---

fragments/k8s/cdk/bundle.yaml
fragments/k8s/core/bundle.yaml

1.8.0 snaps have been released to 1.8/stable. We can do this now.

Bump default snap channels to 1.8/stable

---

fragments/monitor/elastic/bundle.yaml

revs 20 & 21 break with an error about needing Java 8 installed

Need to pin ES for now b/c newer versions break

---

fragments/monitor/elastic/bundle.yaml

Reverts juju-solutions/bundle-canonical-kubernetes#427
Oops, need to revert this. Doesn't work when we pass `--channel edge` to the bundle script.

Revert "Need to pin ES for now b/c newer versions break"

---

bundle

```sh
$ ./bundle -r cs:~containers/etcd,7017 -o bundles/core k8s/core cni/flannel 
rm -rf ./bundles
Processing fragment k8s/core...
Processing fragment cni/flannel...
Done. Your bundle can be found in /home/rye/src/bundle-canonical-kubernetes/bundles/core
$ grep 7017 /home/rye/src/bundle-canonical-kubernetes/bundles/core/bundle.yaml
charm: cs:~containers/etcd-7017
```

allow for overriding charm revisions

---

tests/20-charm-validation.py

Trying to fix flakyness in respective test. Happens often: 
https://ci.kubernetes.juju.solutions/job/build-and-release-all-charms-and-bundles/511/testReport/junit/(root)/bundle/20_charm_validation_py/
https://ci.kubernetes.juju.solutions/job/build-and-release-all-charms-and-bundles/513/testReport/junit/(root)/bundle/20_charm_validation_py/

Increase the timeout for waiting on etcd unit removal

---

fragments/monitor/elastic/bundle.yaml

Update the elastic fragment to use the latest xenial charm versions.
Note: this changes the topology to deploy a single ES unit. I'm not sure why there were 2 units to begin with, but 2 is 1 too many for this fragment.  If users want to scale out their ES bits, they're free to use `juju add-unit`.
Note 2: this configures kibana for port 8080.  Otherwise, if it happens to land on a worker, port 80 might conflict with the ingress controller.

use the latest xenial ES components (fixes #471)

---

tests/40-security-check.py

The `/ui` alias has been removed in 1.10.  Update the test to use the new location of the dashboard (which depends on the k8s version).

update dashboard url

---

tests/20-charm-validation.py

We cannot set labels at deploy time because bundletester will have
already pre-deployed this bundle (subsequent config will get ignored).
Alter test_labels to ensure new labels can be set post deployment.
Fixes #533

fix test_labels in 20-charm-validation

---

tests/20-charm-validation.py

In a handful of local bundletester jobs for cdk-flannel, the time
it takes for the `namespace-delete` action to be reflected by
`namespace-list` ranges from 5-15 seconds.
Increase the sleep time between delete and list to give slower
deletions time to settle.

bump 20-charm-validation test_ns sleep

---

fragments/k8s/cdk/bundle.yaml
fragments/k8s/core/bundle.yaml

We've heard recent reports from the field that cdk won't deploy on Azure. This is because default VMs in Azure come with 1 core and 1.6G ram, which is just barely enough for the apiserver to start, let alone be performant.
Adjust the CDK and k8s-core bundle constraints on k8s-[master|worker] to handle this.  For CDK, both master and workers should have at least 2 cores, 4g ram, and 16g disk.  The minimum for k8s-core is similar, with a minimum of 4 cores for k8s-worker since we only have 1 worker in this setup (note: this is not new, we've always requested 4 cores for the k8s-worker in k8s-core).

adjust constraints for k8s master/workers

---

LICENSE

Hello! 👋
(CCing @dankohn who has requested this work so that the license will appear correctly in https://landscape.cncf.io/selected=canonical-distribution-of-kubernetes)
GitHub uses a library called Licensee to identify a project's license
type. It shows this information in the status bar and via the API if it
can unambiguously identify the license.
This commit updates the LICENSE file so that it contains the full text
of the Apache 2.0 license.  This allows Licensee to successfully
identify the license type of Canonical's codebase as Apache 2.0.

edit Canonical license info so that GitHub recognizes it

---

fragments/k8s/cdk/bundle.yaml

Moving easyrsa to its own machine because 
- bundletester cannot scp to lxc containers.

Move easyrsa in its own machine

---

fragments/k8s/cdk-converged/README.md
fragments/k8s/cdk/README.md
fragments/k8s/core/README.md

As a follow-up to https://github.com/juju-solutions/layer-etcd/issues/122, I looked into our documentation for proxy configuration and found that it needs some updates.
Instead of doing the full edit here, I opted to move the contents over to a wiki page, and update the READMEs to point to the new page: https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Proxy-configuration
Please refer to [Proxy configuration (history)](https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Proxy-configuration/_history) to see the actual changes I made to the content, which is mostly just to use `juju-*-proxy` model configs instead of the older `*-proxy` ones.

Extract "Proxy configuration" documentation to wiki page

---

fragments/monitor/elastic/bundle.yaml

davecore noticed that ES didn't start reliably on GCE.  make sure the bundle sets an appropriate constraint.
Switch to bionic while we're here.  It's been running well for me for a while now.

ES needs at least 4G to start up reliably

---

bundle

Add support for the `post-deployment.sh` script (just like we did for `getstarted.md` in #418). As written, this is a required fragment, so all frag subdirs are getting a zero-length script by default. We could consider making this optional, but that will take some extra work -- presently none of the other fragment files are optional.
This is required for #697.

support post-deployment.sh script

---

bundle

After thinking about #698, it doesn't make sense to have an empty `post-deployment.sh` script in all our fragments. It will cause the juju gui to show the "post deploy" button, even if there's nothing in the file.
Make `post-deployment.sh` optional - do not fail validation when it does not exist, and only write it to the bundle output dir if we have content.

make post-deployment.sh optional

---

fragments/k8s/cdk-converged/post-deployment.sh
fragments/k8s/cdk/post-deployment.sh
fragments/k8s/core/post-deployment.sh

https://github.com/juju/jujushell has added support for post-deployment commands to be run in the gui. This feature in the gui looks for a file in bundles, post-deployment.sh, and sends commands listed there to the jujushell.
Additionally, we'e added a k8s specific post deploy command to the limited shell used in jaas, which this added post-deploy script uses.

Adds post deployment script for jaas/jujushell

---

poc/bundle.yaml

Needed to update this to Bionic anyway, for series compatibility with the subordinate charms deployed by the Graylog/Prometheus addons in conjure-up.

Update NVIDIA bundle for 1.13

---

fragments/cri/containerd/bundle.yaml
fragments/cri/docker/bundle.yaml
fragments/k8s/cdk-converged/bundle.yaml
fragments/k8s/cdk/bundle.yaml
fragments/k8s/core/bundle.yaml

Canal does not work with containerd yet, so the canonical-kubernetes-canal bundle should use docker instead.
This PR makes it possible to select either containerd or docker when building bundles.

Add cri/containerd and cri/docker fragments

---

fragments/cni/calico/bundle.yaml
fragments/cni/canal/bundle.yaml
fragments/cni/flannel/bundle.yaml
fragments/cri/containerd/bundle.yaml
fragments/cri/docker/bundle.yaml
fragments/k8s/cdk-converged/bundle.yaml
fragments/k8s/cdk/bundle.yaml
fragments/k8s/core/bundle.yaml

Re-shuffle the layout to accommodate container runtime subordinate.
https://bugs.launchpad.net/charm-containerd/+bug/1837039

New layout after addition of subordinate runtimes

---

fragments/k8s/core/README.md

URL change for 1.16. Left in original URL as well.

Updating url for dashboard

---

overlays/vault-pki-overlay.yaml

The bundle overlays are being moved out of the docs repo and into the bundle repo.

Add vault-pki-overlay.yaml from docs

---

overlays/logging-egf-overlay.yaml

The ELK stack is now at v6 and graylog officially supports v3.  Rich k8s metadata can now be collected with a simple overlay.
Fixes #651

add elastic/graylog/filebeat overlay

---

fragments/k8s/cdk/bundle.yaml
fragments/k8s/core/bundle.yaml

Tested with overlay.  Have run etcd validation tests against 3.3 and they pass.

Etcd 3.3 by default

---

overlays/logging-egf-overlay.yaml

Related to https://bugs.launchpad.net/cdk-addons/+bug/1858651.  Stop locking charm revisions in our logging overlay since we always want latest stable charms.

default to latest stable charms in logging overlay

---

overlays/openstack-lb-overlay.yaml

The kube-api-endpoint relation was originally being proxied between k8s-master and k8s-worker via kubeapi-load-balancer, but with that being removed, needs to be directly established between the master and worker.

Add missing kube-api-endpoint relation in OpenStack LB overlay

---

overlays/ceph-fs.yaml

There was a mismatch between the storage settings in the ceph-fs overlay vs ceph-rbd, and the former also had an errant test value in the options for `osd-devices`.

Update ceph-fs overlay to match ceph-rbd

---

bundle

PR #786 removed the Amulet tests, since Amulet has been deprecated for a long time, but the bundle builder script still referenced them, so started failing.

Finish removing unused Amulet tests

---

fragments/k8s/cdk-converged/README.md
fragments/k8s/cdk-converged/bundle.yaml
fragments/k8s/cdk/README.md
fragments/k8s/cdk/bundle.yaml
fragments/k8s/core/README.md
fragments/k8s/core/bundle.yaml

For the CK 1.21 RC release. The stable branches have already been reset to master, therefore, this PR is targeted against stable.

Bump k8s snap channels to 1.21/stable

---

fragments/k8s/cdk-converged/README.md
fragments/k8s/cdk-converged/bundle.yaml
fragments/k8s/cdk/README.md
fragments/k8s/cdk/bundle.yaml
fragments/k8s/core/README.md
fragments/k8s/core/bundle.yaml

1.21 is now stable. Per [release doc](http://jenkaas.s3-website-us-east-1.amazonaws.com/docs/releases/stable/#update-ck-bundle-repo-references), edge bundles from master branch should move up to 1.22.

new edge bundles should come from 1.22/edge

---

BUILD.md
bundle
fragments/cni/calico/bundle.yaml
fragments/cni/canal/bundle.yaml
fragments/cni/flannel/bundle.yaml
fragments/cni/tigera-secure-ee/bundle.yaml
fragments/cri/containerd/bundle.yaml
fragments/cri/docker/bundle.yaml
fragments/k8s/cdk-converged/bundle.yaml
fragments/k8s/cdk/bundle.yaml
fragments/k8s/core/bundle.yaml
fragments/legacy-storage/ceph/bundle.yaml
fragments/monitor/elastic/bundle.yaml

Juju 2.9 now emits warnings about the use of 'services' in bundles rather than applications [LP#1913779](https://bugs.launchpad.net/charmed-kubernetes-bundles/+bug/1913779)
We should switch to applications so we don't get warnings and the bundle continues to work in Juju 3.0

services->applications

---

overlays/azure-overlay.yaml

With the addition of the load balancer relation endpoints, the relation between k8s-master and the azure-integrator becomes ambiguous, so this qualifies it in the overlay.

Qualify Azure integration relation endpoint

---

fragments/k8s/cdk-converged/bundle.yaml
fragments/k8s/cdk/bundle.yaml
fragments/k8s/core/bundle.yaml

In preparation for the 1.22 release, make 1.22/stable the default channel in the `stable` branch.

make 1.22/stable the default channel

---

fragments/k8s/cdk-converged/bundle.yaml
fragments/k8s/cdk/bundle.yaml
fragments/k8s/core/bundle.yaml

In preparation for the 1.23 release, make 1.23/stable the default channel in the `stable` branch.

make 1.23/stable the default channel

---

overlays/aws-overlay.yaml
overlays/azure-overlay.yaml
overlays/bdc-overlay.yaml
overlays/calico-overlay.yaml
overlays/canal-overlay.yaml
overlays/ceph-fs.yaml
overlays/ceph-rbd.yaml
overlays/equinix-overlay.yaml
overlays/gcp-overlay.yaml
overlays/ipv4-ipv6-overlay.yaml
overlays/logging-egf-overlay.yaml
overlays/monitoring-pgt-overlay.yaml
overlays/openstack-lb-overlay.yaml
overlays/openstack-overlay.yaml
overlays/tigera-overlay.yaml
overlays/vault-pki-ha-overlay.yaml
overlays/vault-pki-overlay.yaml
overlays/vsphere-overlay.yaml

at date, charmhub CDK charms haven't reached a stable release on charmhub and therefore shouldn't be included
Evidence that the following overlays can be applied to the current latest/stabe `charmed-kubernetes` bundle 
https://paste.ubuntu.com/p/yysQbGZVRY/

revert overlays to use charmstore charms until a 1.24 release 

---

fragments/k8s/core/bundle.yaml

related k8s-cp was to itself rather than k8s-worker

fix issue with inclusive naming in the kubernetes-core bundle 

---

fragments/k8s/cdk/bundle.yaml
fragments/k8s/core/bundle.yaml

In preparation of the 1.24 release, revisit our bundle defaults to use `1.24/edge` snaps and adjust hardware constraints.
- Bump etcd reqs to [small cluster](https://etcd.io/docs/v3.3/op-guide/hardware/#small-cluster) recommendation
- Bump k-c-p and worker mem to 8G. I took some cues from [openshift reqs](https://docs.openshift.com/container-platform/3.11/install/prerequisites.html) -- a bit smaller for our control plane, a bit bigger for our workers.
- Bump all root-disks to 16GB; 8 was cutting it too close for long-running clusters (/var/log fills up)
Note: we don't specify charm channels in these yamls because our bundle builder injects those.

adjust snap channels and constraints for 1.24

---

overlays/aws-overlay.yaml
overlays/azure-overlay.yaml
overlays/bdc-overlay.yaml
overlays/calico-overlay.yaml
overlays/canal-overlay.yaml
overlays/ceph-fs.yaml
overlays/ceph-rbd.yaml
overlays/equinix-overlay.yaml
overlays/gcp-overlay.yaml
overlays/ipv4-ipv6-overlay.yaml
overlays/logging-egf-overlay.yaml
overlays/monitoring-pgt-overlay.yaml
overlays/openstack-lb-overlay.yaml
overlays/openstack-overlay.yaml
overlays/tigera-overlay.yaml
overlays/vault-pki-ha-overlay.yaml
overlays/vault-pki-overlay.yaml
overlays/vsphere-overlay.yaml

Reverts charmed-kubernetes/bundle#833
Wrong branch; this needs to go to main and then cherry-pick to stable.

Revert "update overlays to reference 1.24/stable charms"

---

bundle

Creates bundles such that if the `--channel=latest/stable` or `--channel=stable`, the same exact bundles are produced where the charm channels reference the risk channel only. 
If the `--channel=1.24/beta` is specified, it will error on any charm in the fragment which references a "cs:" reference.

Enforce built bundles include appropriate charm channels

---

overlays/openstack-lb-overlay.yaml

Fixes https://bugs.launchpad.net/charmed-kubernetes-bundles/+bug/1974280

Remove kube-api-endpoint relation from openstack overlay

---

overlays/canal-overlay.yaml

Fixes https://bugs.launchpad.net/charmed-kubernetes-bundles/+bug/1980084
Starting with Charmed Kubernetes 1.24 the default CNI implementation is Calico. The Canal overlay needs to remove Calico, not Flannel.

Fix Canal overlay not removing Calico

---

overlays/vault-pki-ha-overlay.yaml
overlays/vault-pki-overlay.yaml
overlays/vault-storage-overlay.yaml

Our vault overlays offer a bionic-only backend.  Update these for focal using `mysql-innodb-cluster` instead of `percona-cluster`.
Update the pki-ha overlay to include HA requirements from the [Charmed Openstack HA App guidelines](https://docs.openstack.org/charm-guide/latest/admin/ha.html#ha-applications). Note: in this scenario, `easyrsa` is required to bootstrap `etcd` for use by `vault`, hence the overlay does not remove the `easyrsa` application.
Also add a new storage overlay for people that want a secure db without the pki cert stuff.
Fixes https://bugs.launchpad.net/charmed-kubernetes-bundles/+bug/1946290

update vault overlays

---

overlays/kube-ovn-overlay.yaml

This is needed for the Kube-OVN documentation.
This overlay doesn't work yet, but should work once we get a kube-ovn charm release out to stable.

Add kube-ovn-overlay.yaml

---

fragments/k8s/cdk-converged/bundle.yaml
fragments/k8s/cdk/bundle.yaml
fragments/k8s/core/bundle.yaml

In preparation for the 1.25 release, make 1.25/stable the default snap channel in the release branch.

make 1.25/stable the default snap channel for release_1.25

---

overlays/monitoring-pgt-overlay.yaml

Couple tweaks in our monitoring overlay came in via https://github.com/charmed-kubernetes/kubernetes-docs/pull/722.  I've confirmed these changes look good with the latest 1.25+ck1 bundle.

update pgt overlay with current recommendations

---

overlays/ceph-radosgw.yaml

This PR fixes a typo in the applications.ceph-osd.storage.osd-devices config line that prevented the charm from installing.
From `ods-device`: to `ods-devices`.
This file is directly referenced in the Equinix Metal Charmed Kubernetes documentation here: https://ubuntu.com/kubernetes/docs/equinix
Signed-off-by: Chris Privitere <23177737+cprivitere@users.noreply.github.com>

Fix typo in ceph-osd charm config

---

fragments/k8s/cdk-converged/bundle.yaml
fragments/k8s/cdk/bundle.yaml
fragments/k8s/core/bundle.yaml

Related to https://bugs.launchpad.net/bugs/2007162
I would say the main branches and latest/edge channels mostly represent development for k8s 1.27 at this point, so I propose we update the charm and bundle defaults to 1.27/edge.

Update snap channel to 1.27/edge

---

Makefile
fragments/cni/cilium/README.md
fragments/cni/cilium/bundle.yaml

The fragments for cilium in 1.27 isn't here.
```
bob@bob:/tmp/bundle$ ./bundle --channel=1.27/stable "k8s/cdk" "cni/cilium" "cri/containerd" -o "/tmp/bob"
Traceback (most recent call last):
File "/tmp/bundle/./bundle", line 329, in <module>
main()
File "/tmp/bundle/./bundle", line 254, in main
validate_components(args.fragments)
File "/tmp/bundle/./bundle", line 81, in validate_components
raise FragmentUnknown('Unknown fragment ' + frag)
__main__.FragmentUnknown: Unknown fragment cni/cilium
```
Added, and updated the Makefile
```
$ ./bundle --channel=1.27/stable "k8s/cdk" "cni/cilium" "cri/containerd" -o "/tmp/bob"
Processing fragment k8s/cdk...
Processing fragment cni/cilium...
Processing fragment cri/containerd...
Done. Your bundle can be found in /tmp/bob
```

Add cilium fragments

---

overlays/cilium-overlay.yaml

[LP#2032533](https://bugs.launchpad.net/charmed-kubernetes-bundles/+bug/2032533)
For cilium deployments, it's imperative that `rp_filter` not be defaulted to 1
See: https://github.com/cilium/cilium/issues/20498

override default `net.ipv4.conf.all.rp_filter` to 0

---

fragments/k8s/cdk-converged/README.md
fragments/k8s/cdk-converged/bundle.yaml
fragments/k8s/cdk/README.md
fragments/k8s/cdk/bundle.yaml
fragments/k8s/core/README.md
fragments/k8s/core/bundle.yaml

* bump snap channel defaults from 1.28/edge to 1.29/edge
* update bundle in the charm READMEs

update fragments to point to 1.29/edge snap channels

---

overlays/openstack-lb-overlay.yaml
overlays/openstack-overlay.yaml

[LP#1940328](https://bugs.launchpad.net/charm-openstack-integrator/+bug/1940328)
With the removal of the `loadbalancer` relation in the `kubernetes-control-plane`, the overlays to deploy on openstack need to be explicitly updated.

[LP#1940328] Update openstack-integrator overlays for 1.29

---

fragments/k8s/cdk-converged/bundle.yaml
fragments/k8s/cdk/bundle.yaml
fragments/k8s/core/bundle.yaml

Rather than using `series`, use `default-base` in our charmed-kubernetes bundles
Since juju 3.1, the preferred method of specifying the machine version is to use bases rather than named series.  Now that charmed-kubernetes only supports juju 3, lets finally fix this
* Using this unlocks support for noble (ubuntu@24.04) -- deploying a bundle without a `default-base` sent the juju client off looking for a  base for the machines.  It encountered charms with bases the client didn't recognize that caused deployments to fail.

Use default-base rather than series

---

overlays/openstack-lb-overlay.yaml

> ERROR cannot deploy bundle: cannot add relation between "kubernetes-control-plane:loadbalancer-external" and "openstack-integrator:lb-consumer": application "openstack-integrator" has no "lb-consumer" relation

Fix typo in the relation name of lb-consumers

---

fragments/k8s/cdk-converged/README.md
fragments/k8s/cdk-converged/bundle.yaml
fragments/k8s/cdk/bundle.yaml
fragments/k8s/core/bundle.yaml

This PR updates the k8s version according to the [release doc](https://github.com/charmed-kubernetes/jenkins/blob/main/docs/releases/stable/index.md#pin-snap-channel-for-charms-in-the-release-branches)

chore: 1.33 release readiness

---

fragments/k8s/cdk/bundle.yaml
fragments/k8s/core/bundle.yaml

WIP: Need to create a bug on JIRA for tracking
Description:
* If one sets the `default-base` in a bundle, nothing can be done to override this `default-base` in a bundle overlay.
* In order to test on both jammy and noble, we must remove the `default-base`
* without a overlay bundle, the base for each charm will follow the most recently supported LTS by the charm
*  this seems to be part of juju that i've determined emperically
* I think there's a bug on juju where the `default-base` of a bundle should be allowed to be overridden.
Based on the discussion [here](https://matrix.to/#/!xzmWHtGpPfVCXKivIh:ubuntu.com/$f8P89MyMu-t7o_wYWiyd9LZryfvM9O6FmA-EPEICiEw?via=ubuntu.com&via=matrix.org&via=xentonix.net)

Allow for flexible base-selection within a model using overlays
